service: test
plugins:
  modules:
    - '@ananke/serverless'
    - serverless-pseudo-parameters
    - serverless-offline
package:
  exclude:
    - src/**
    - test/**
    - venv/**
    - node_modules/aws-sdk/**
    - node_modules/serverless/**
  include:
    - lib/**
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 20
  region: us-east-1
  stage: ${opt:stage, 'development'}
  environment:
    NODE_ENV: ${opt:environment, 'development'}
    LOG_LEVEL: 10
functions:
custom:
  ananke:
    function:
      context: './lib/context'
      source: './lib/functions'
      onError: './lib/functions/error'
    rpc:
      path: /
      methods: './lib/functions/rpc'
      authenticator: './lib/functions/rpc/authenticator'
    rest:
      authenticator: './lib/functions/rpc/authenticator'